WSGIDaemonProcess cdeadmin processes=1 threads=25 python-home=/usr/cdeadmin/venv
WSGIScriptAlias /cdeadmin /usr/cdeadmin/web/CDEadmin.wsgi

<Directory /usr/cdeadmin/web/>
    WSGIProcessGroup cdeadmin
    WSGIApplicationGroup %{GLOBAL}
    Require all granted
</Directory>
