#!/usr/bin/env python3
##########################################################################
# CDEadmin - Multi-engine Database Administration
# Copyright (C) 2013 - 2026, The pgAdmin Development Team
# This software is released under the PostgreSQL Licence
##########################################################################

"""Observe column-action admission; not a full capability certificate."""

import argparse
import json
import traceback
import uuid
from pathlib import Path, PurePosixPath
from types import SimpleNamespace

from cdeadmin_firebird_admin_mapping_gate import (
    _create_client, _route_arguments, _resources,
)
from pgadmin.cdeadmin.providers.firebird.provider import (
    _materialize_catalog_value,
)

CLAUSES = {
    'POSITION': 'POSITION 2',
    'SET NOT NULL': 'SET NOT NULL',
    'DROP NOT NULL': 'DROP NOT NULL',
    'SET DEFAULT': 'SET DEFAULT 42',
    'DROP DEFAULT': 'DROP DEFAULT',
    'TYPE': 'TYPE BIGINT',
    'COMPUTED': 'COMPUTED BY (X + 1)',
    'TYPE COMPUTED': 'TYPE BIGINT COMPUTED BY (X + 1)',
    'IDENTITY': 'SET GENERATED BY DEFAULT',
    'DROP IDENTITY': 'DROP IDENTITY',
    'TYPE BLOB BINARY': 'TYPE BLOB SUB_TYPE BINARY',
    'TYPE BLOB TEXT': 'TYPE BLOB SUB_TYPE TEXT',
}


def run(profiles):
    import firebird.driver as driver
    document = json.loads(profiles.read_text())
    route = next(dict(item) for item in document['profiles']
                 if item['engine'] == 'firebird')
    route.setdefault('host', document.get('host', '127.0.0.1'))
    filename = 'cde_column_context_' + uuid.uuid4().hex + '.fdb'
    route['database'] = str(PurePosixPath(route['database']).parent / filename)
    _create_client(SimpleNamespace(acquire_secret=None))
    connection = driver.create_database(password=route['password'],
                                        **_route_arguments(route, driver))
    tpb = driver.tpb(driver.Isolation.SNAPSHOT, lock_timeout=5)
    connection.default_tpb = tpb
    connection.main_transaction.default_tpb = tpb
    result = {'complete': False, 'observations': [], 'failures': [],
              'fixture_database': route['database'], 'fixture_removed': False,
              'qualification_claim': False, 'catalog_checks': []}

    def execute(sql):
        with connection.cursor() as cursor:
            cursor.execute(sql)

    def state():
        with connection.cursor() as cursor:
            cursor.execute(
                'SELECT RF.RDB$NULL_FLAG, RF.RDB$DEFAULT_SOURCE, '
                'RF.RDB$IDENTITY_TYPE, RF.RDB$FIELD_POSITION, '
                'F.RDB$FIELD_TYPE, F.RDB$FIELD_SUB_TYPE, '
                'F.RDB$FIELD_SCALE, F.RDB$COMPUTED_SOURCE '
                'FROM RDB$RELATION_FIELDS RF JOIN RDB$FIELDS F ON '
                'F.RDB$FIELD_NAME = RF.RDB$FIELD_SOURCE WHERE '
                "RF.RDB$RELATION_NAME = 'T' AND RF.RDB$FIELD_NAME = 'V'")
            value = [_materialize_catalog_value(item)
                     for item in cursor.fetchone()]
        connection.commit()
        return value

    variants = {
        'stored-nullable': 'INTEGER',
        'stored-not-null': 'INTEGER NOT NULL',
        'local-default': 'INTEGER DEFAULT 7',
        'domain-default': 'DD',
        'array': 'INTEGER[1:3]',
        'primary-key': 'INTEGER PRIMARY KEY',
        'computed': 'INTEGER COMPUTED BY (X + 1)',
        'identity': 'BIGINT GENERATED ALWAYS AS IDENTITY',
        'domain-nullable': 'D',
        'domain-not-null': 'DNN',
        'blob': 'BLOB SUB_TYPE BINARY',
        'view': None,
    }
    try:
        with connection.cursor() as cursor:
            cursor.execute("SELECT RDB$GET_CONTEXT('SYSTEM','ENGINE_VERSION') "
                           'FROM RDB$DATABASE')
            result['engine_version'] = cursor.fetchone()[0]
        connection.commit()
        assert result['engine_version'] == '5.0.4'
        execute('CREATE DOMAIN D AS INTEGER')
        execute('CREATE DOMAIN DNN AS INTEGER NOT NULL')
        execute('CREATE DOMAIN DD AS INTEGER DEFAULT 7')
        execute('CREATE TABLE P (X INTEGER, V INTEGER)')
        connection.commit()
        for kind, definition in variants.items():
            for action, clause in CLAUSES.items():
                label = kind + ':' + action
                try:
                    execute('CREATE VIEW T AS SELECT X, V FROM P' if
                            kind == 'view' else
                            'CREATE TABLE T (X INTEGER, V ' + definition + ')')
                    connection.commit()
                    if action == 'POSITION':
                        resources = _resources(connection, {'route': route})
                        connection.commit()
                        native = next(item['native'] for item in resources
                                      if item['resource_kind'] == 'column' and
                                      item['display_path'] == ['T', 'V'])
                        allowed = native['alteration']['allowed_actions']
                        expected = [] if kind == 'view' else [
                            'POSITION', 'SET NOT NULL', 'TYPE']
                        if kind != 'view':
                            if kind in {'array', 'blob'}:
                                expected.remove('TYPE')
                            if kind not in {'identity', 'primary-key'}:
                                expected.append('DROP NOT NULL')
                            if kind not in {'computed', 'identity', 'array'}:
                                expected.append('SET DEFAULT')
                            if kind == 'local-default':
                                expected.append('DROP DEFAULT')
                            if kind == 'computed':
                                expected.remove('TYPE')
                                expected.extend(['COMPUTED', 'TYPE COMPUTED'])
                            if kind == 'identity':
                                expected.extend(['IDENTITY', 'DROP IDENTITY'])
                        assert set(allowed) == set(expected), (kind, allowed)
                        assert native['alteration']['position'] == 2
                        result['catalog_checks'].append({
                            'column_kind': kind, 'allowed_actions': allowed,
                            'position': 2})
                    before = state()
                    sql = 'ALTER TABLE T ALTER COLUMN V ' + clause
                    observation = {'column_kind': kind, 'action': action,
                                   'statement': sql}
                    try:
                        execute(sql)
                        observation['accepted'] = True
                    except driver.DatabaseError as error:
                        observation.update(accepted=False,
                                           sqlcode=error.sqlcode,
                                           gds_codes=error.gds_codes,
                                           native_message=str(error))
                    finally:
                        if connection.main_transaction.is_active():
                            connection.rollback()
                    assert state() == before, 'rollback changed metadata'
                    observation['rollback_preserved'] = True
                    result['observations'].append(observation)
                except Exception:
                    result['failures'].append({
                        'case': label, 'traceback': traceback.format_exc()})
                finally:
                    if connection.main_transaction.is_active():
                        connection.rollback()
                    execute('DROP VIEW T' if kind == 'view' else
                            'DROP TABLE T')
                    connection.commit()
    except Exception:
        result['failures'].append({'case': 'infrastructure',
                                   'traceback': traceback.format_exc()})
    finally:
        try:
            if connection.main_transaction.is_active():
                connection.rollback()
            connection.drop_database()
            result['fixture_removed'] = True
        except Exception:
            result['failures'].append({'case': 'fixture-cleanup',
                                       'traceback': traceback.format_exc()})
    result['expected_observations'] = len(variants) * len(CLAUSES)
    result['complete'] = (not result['failures'] and result['fixture_removed']
                          and len(result['observations']) ==
                          result['expected_observations'] and
                          len(result['catalog_checks']) == len(variants))
    return result


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument('--profiles', type=Path, required=True)
    parser.add_argument('--output', type=Path, required=True)
    args = parser.parse_args()
    result = run(args.profiles)
    args.output.parent.mkdir(parents=True, exist_ok=True)
    args.output.write_text(json.dumps(result, indent=2) + '\n')
    print(json.dumps({'complete': result['complete'],
                      'observations': len(result['observations']),
                      'failures': len(result['failures'])}))
    return 0 if result['complete'] else 1


if __name__ == '__main__':
    raise SystemExit(main())
